# See https://github.com/nmayorga092/revanced/blob/main/CONFIG.md for more detailed explanations

[main-config]
compression-level = 9               # compression level for module zips. between 1 and 9
enable-magisk-update = false        # set this to false if you do not want to receive updates from magisk app
parallel-jobs = 3                   # max number of concurrent building jobs
update-prebuilts = true             # dont touch this
build-mindetach-module = false


[YouTube]
enabled = false                                                                                       # add 'enabled = false' key to entries to not build them
build-mode = "module"                                                                                 # 'both', 'apk' or 'module'
excluded-patches = "debugging return-youtube-dislike custom-branding swipe-controls downloads"        # whitespace seperated list of patches to exclude
included-patches = ""                                                                                 # whitespace seperated list of patches to include
version = "auto"                                                                                      # 'auto', 'latest' or a custom one like '17.40.41'
exclusive-patches = false                                                                             # excludes all patches by default
microg-patch = "microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube/"
module-prop-name = "ytrv-magisk"
merge-integrations = true
rip-libs = true

[Music-arm64]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-magisk"
arch = "arm64-v8a"

[Music-arm]
enabled = false
build-mode = "both"
app-name = "Music"
excluded-patches = ""
included-patches = ""
version = "auto"
microg-patch = "music-microg-support"
apkmirror-dlurl = "https://www.apkmirror.com/apk/google-inc/youtube-music/"
module-prop-name = "ytmusicrv-arm-magisk"
arch = "arm-v7a"

[Twitter]
enabled = false
build-mode = "apk"
excluded-patches = "hide-views-stats"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitter-inc/twitter/"

[Reddit]
enabled = false
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/redditinc/reddit/"

[Twitch]
enabled = true
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/twitch-interactive-inc/twitch/"
merge-integrations = true

[TikTok]
build-mode = "apk"
version = "27.2.5"
apkmirror-dlurl = "https://www.apkmirror.com/apk/tiktok-pte-ltd/tik-tok-including-musical-ly/"
merge-integrations = true

[Spotify]
enabled = false
build-mode = "apk"
version = "latest"
uptodown-dlurl = "https://spotify.en.uptodown.com/android"

[Citra]
enabled = false
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/citra-emulator/citra-emulator/"

[Backdrops]
enabled = false
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/backdrops/backdrops-wallpapers/"

[WarnWetter]
enabled = false
version = "latest"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/deutscher-wetterdienst/warnwetter/"

[Windyapp]
enabled = false
version = "latest"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/windy-weather-world-inc/windy-wind-weather-forecast/"

[MyExpenses]
enabled = false
version = "latest"
build-mode = "apk"
uptodown-dlurl = "https://my-expenses.en.uptodown.com/android"

[NyxMusicPlayer]
enabled = false
version = "latest"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/awedea/nyx-music-player/"

[IconPackStudio]
enabled = true
version = "latest"
build-mode = "apk"
apkmirror-dlurl = "https://www.apkmirror.com/apk/smart-launcher-team/icon-pack-studio/"

[TickTick]
enabled = false
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/appest-inc/ticktick-to-do-list-with-reminder-day-planner/"

[Tasker]
enabled = false
build-mode = "apk"
version = "latest"
apkmirror-dlurl = "https://www.apkmirror.com/apk/joaomgcd/tasker/"
